In [1]:
import numpy as np

In [18]:
a = np.arange(1, 13)
a.resize(3, 4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
row = a[1, :]
col = a[:, 2]
print(row, col)

[5 6 7 8] [ 3  7 11]


In [32]:
b = np.random.randint(0, 21, 10)
print(b[b % 2 == 0])

[18  8  2]


In [36]:
b = np.random.randint(0, 10, (5, 5))
print(np.sum(b, axis = 0), np.sum(b, axis = 1))

[30 27 22 25 30] [30 32 24 24 24]


In [41]:
e = np.ones((2, 3))
g = np.zeros((2, 3))
c = np.hstack((e, g))
print(c)
d = np.vstack((e, g))
print(d)

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
z = np.arange(16).reshape(4, 4)
print(np.split(z, 2, axis = 1))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [51]:
A = np.arange(6).reshape(2,3)
B = ([[20], [30]])
print(A + B)

[[20 21 22]
 [33 34 35]]


In [54]:
m = np.array([[2, 1], [1, 3]])
print(m)
print(np.linalg.det(m))
print(np.linalg.inv(m))
print(np.linalg.eig(m))

[[2 1]
 [1 3]]
5.000000000000001
[[ 0.6 -0.2]
 [-0.2  0.4]]
EigResult(eigenvalues=array([1.38196601, 3.61803399]), eigenvectors=array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]]))
